/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omsay9559
 */
public class ZirbonMoney extends javax.swing.JFrame {

    /**
     * Creates new form ZirbonMoney
     */
    public ZirbonMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        inputLbl = new javax.swing.JLabel();
        inputAmt = new javax.swing.JTextField();
        drobzitsLbl = new javax.swing.JLabel();
        drobzitsAmt = new javax.swing.JTextField();
        clickwicksLbl = new javax.swing.JLabel();
        clickwicksAmt = new javax.swing.JTextField();
        gazoontightLbl = new javax.swing.JLabel();
        gazoontightAmt = new javax.swing.JTextField();
        frazointAmt = new javax.swing.JTextField();
        frazointLbl = new javax.swing.JLabel();
        blointointLbl = new javax.swing.JLabel();
        blointointAmt = new javax.swing.JTextField();
        vrobitLbl = new javax.swing.JLabel();
        vrobitAmt = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("RomanC", 0, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 0, 0));
        titleLbl.setText("Zirboin Financial");

        inputLbl.setText("Enter the amount of vrobits you have:");

        inputAmt.setText("0");
        inputAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAmtActionPerformed(evt);
            }
        });

        drobzitsLbl.setText("The amount of Drobzits you should recieve is:  ");

        drobzitsAmt.setText("0");
        drobzitsAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drobzitsAmtActionPerformed(evt);
            }
        });

        clickwicksLbl.setText("The amount of Clickwicks you should recieve is:  ");

        clickwicksAmt.setText("0");
        clickwicksAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickwicksAmtActionPerformed(evt);
            }
        });

        gazoontightLbl.setText("The amount of Gazoontights you should recieve is:  ");

        gazoontightAmt.setText("0");
        gazoontightAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gazoontightAmtActionPerformed(evt);
            }
        });

        frazointAmt.setText("0");
        frazointAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frazointAmtActionPerformed(evt);
            }
        });

        frazointLbl.setText("The amount of Frazoints you should recieve is:  ");

        blointointLbl.setText("The amount of Blointoints you should recieve is:  ");

        blointointAmt.setText("0");
        blointointAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blointointAmtActionPerformed(evt);
            }
        });

        vrobitLbl.setText("The amount of Vrobits you should recieve is:  ");

        vrobitAmt.setText("0");
        vrobitAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vrobitAmtActionPerformed(evt);
            }
        });

        calculateBtn.setText("Calculate ");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(titleLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputLbl)
                                .addGap(18, 18, 18)
                                .addComponent(inputAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(frazointLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(frazointAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(clickwicksLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(clickwicksAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(drobzitsLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drobzitsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(gazoontightLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(gazoontightAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(vrobitLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(vrobitAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(blointointLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(blointointAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(calculateBtn)
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLbl)
                    .addComponent(inputAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(calculateBtn)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drobzitsLbl)
                    .addComponent(drobzitsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clickwicksLbl)
                    .addComponent(clickwicksAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gazoontightLbl)
                    .addComponent(gazoontightAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frazointLbl)
                    .addComponent(frazointAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blointointLbl)
                    .addComponent(blointointAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vrobitLbl)
                    .addComponent(vrobitAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAmtActionPerformed

    private void drobzitsAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drobzitsAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drobzitsAmtActionPerformed

    private void clickwicksAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickwicksAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clickwicksAmtActionPerformed

    private void gazoontightAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gazoontightAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gazoontightAmtActionPerformed

    private void frazointAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frazointAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frazointAmtActionPerformed

    private void blointointAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blointointAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blointointAmtActionPerformed

    private void vrobitAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vrobitAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vrobitAmtActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
      int amtOfVrobits, amtOfDrobzits, amtOfClickwicks, amtOfGazoontights, amtOfFrazoints, amtOfBlointoints, amtOfVrobitsLeft;
      int amtOfDrobzitsLeft, amtOfClickwicksLeft, amtOfGazoontightsLeft, amtOfFrazointsLeft, amtOfBlointointsLeft;
     
      amtOfVrobits  =Integer.parseInt(inputAmt.getText());
      
      amtOfDrobzits = amtOfVrobits / 100000;
      amtOfDrobzitsLeft = amtOfVrobits % 100000;
      
      amtOfClickwicks = amtOfDrobzitsLeft / 50000;
      amtOfClickwicksLeft = amtOfDrobzitsLeft % 50000;
      
      
        
        
        
        
    }//GEN-LAST:event_calculateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZirbonMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZirbonMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZirbonMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZirbonMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZirbonMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blointointAmt;
    private javax.swing.JLabel blointointLbl;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JTextField clickwicksAmt;
    private javax.swing.JLabel clickwicksLbl;
    private javax.swing.JTextField drobzitsAmt;
    private javax.swing.JLabel drobzitsLbl;
    private javax.swing.JTextField frazointAmt;
    private javax.swing.JLabel frazointLbl;
    private javax.swing.JTextField gazoontightAmt;
    private javax.swing.JLabel gazoontightLbl;
    private javax.swing.JTextField inputAmt;
    private javax.swing.JLabel inputLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField vrobitAmt;
    private javax.swing.JLabel vrobitLbl;
    // End of variables declaration//GEN-END:variables
}
