/*
 * Omar Sayyed
 * Jan 25th 2019 
 * Friends multiple choice trivia quiz for Cumalitive Project
 * This is frame 2/2 which contains the questions, and the leaderboard, along with alll of the supporting scorekeeping
 */


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;



/**
 *
 * @author omsay9559
 */
public class QuestionsScreen extends javax.swing.JFrame {
int questionNum = 0;
double incorrectScore = 0;
double correctScore = 0;
    /**
     * Creates new form QuestionsScreen
     */
    public QuestionsScreen() {
        initComponents();
    textOut.setVisible(false);
    jScrollPane1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionLbl0 = new javax.swing.JLabel();
        ansALbl0 = new javax.swing.JLabel();
        ansBLbl0 = new javax.swing.JLabel();
        ansCLbl0 = new javax.swing.JLabel();
        ansDLbl0 = new javax.swing.JLabel();
        answerPromptLbl0 = new javax.swing.JLabel();
        userAnswer0 = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        numCorrectLbl = new javax.swing.JLabel();
        numIncorrectLbl = new javax.swing.JLabel();
        perCorrectLbl = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        youAreUserLbl = new javax.swing.JLabel();
        numCorrectNum = new javax.swing.JLabel();
        numIncorrectNum = new javax.swing.JLabel();
        perCorrectNum = new javax.swing.JLabel();
        nextQBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textOut = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        questionLbl0.setFont(new java.awt.Font("Manga Temple", 0, 24)); // NOI18N
        questionLbl0.setForeground(new java.awt.Color(204, 0, 0));
        questionLbl0.setText("How many categories of towels does Monica Have?");

        ansALbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansALbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansALbl0.setText("A) 9");

        ansBLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansBLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansBLbl0.setText("B) 7");

        ansCLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansCLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansCLbl0.setText("C) 11");

        ansDLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ansDLbl0.setForeground(new java.awt.Color(204, 0, 0));
        ansDLbl0.setText("D) 13");

        answerPromptLbl0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerPromptLbl0.setForeground(new java.awt.Color(204, 0, 0));
        answerPromptLbl0.setText("Enter Your answer here:");

        userAnswer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAnswer0ActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(204, 0, 0));
        submitBtn.setText("Submit Answer");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        numCorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numCorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        numCorrectLbl.setText("Number Correct:");

        numIncorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numIncorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        numIncorrectLbl.setText("Number Incorrect:");

        perCorrectLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perCorrectLbl.setForeground(new java.awt.Color(204, 0, 0));
        perCorrectLbl.setText("Percentage Correct:");

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/friendsLogo.png"))); // NOI18N

        youAreUserLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        youAreUserLbl.setForeground(new java.awt.Color(204, 0, 0));
        youAreUserLbl.setText("You are user #");

        numCorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numCorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        numCorrectNum.setText("0");

        numIncorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numIncorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        numIncorrectNum.setText("0");

        perCorrectNum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        perCorrectNum.setForeground(new java.awt.Color(204, 0, 0));
        perCorrectNum.setText("0");

        nextQBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextQBtn.setForeground(new java.awt.Color(204, 0, 0));
        nextQBtn.setText("Next Question");
        nextQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQBtnActionPerformed(evt);
            }
        });

        textOut.setColumns(20);
        textOut.setRows(5);
        jScrollPane1.setViewportView(textOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numIncorrectLbl)
                            .addComponent(perCorrectLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(youAreUserLbl)
                                .addGap(12, 12, 12))
                            .addComponent(numCorrectLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numCorrectNum)
                            .addComponent(perCorrectNum)
                            .addComponent(numIncorrectNum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(picture))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ansALbl0)
                        .addGap(18, 18, 18)
                        .addComponent(ansBLbl0)
                        .addGap(18, 18, 18)
                        .addComponent(ansCLbl0)
                        .addGap(18, 18, 18)
                        .addComponent(ansDLbl0))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(questionLbl0))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(answerPromptLbl0))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(userAnswer0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(nextQBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(questionLbl0)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ansALbl0)
                            .addComponent(ansBLbl0)
                            .addComponent(ansCLbl0)
                            .addComponent(ansDLbl0))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerPromptLbl0)
                            .addComponent(userAnswer0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextQBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numCorrectLbl)
                                    .addComponent(numCorrectNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numIncorrectLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(perCorrectLbl))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(numIncorrectNum)
                                    .addGap(1, 1, 1)
                                    .addComponent(perCorrectNum))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(youAreUserLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userAnswer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAnswer0ActionPerformed

    }//GEN-LAST:event_userAnswer0ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        //declare variables
        String answer0, correctPercentage, scoreFinal;
     
        double perCorrect, userNum;
//        nextQBtn.setVisible(true);
       
        
        

        //get user's answers
        answer0 =userAnswer0.getText();
        

        //Check answers for questions
        if (questionNum == 0){
        switch (answer0) {
            case "C":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "c":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        } else if(questionNum == 1){
        switch (answer0) {
            case "C":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "c":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        }else if(questionNum == 2){
        switch (answer0) {
            case "B":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "b":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        }else if(questionNum == 3){
        switch (answer0) {
            case "A":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "a":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        }else if(questionNum == 4){
        switch (answer0) {
            case "B":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "b":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        }else if(questionNum == 5){
        switch (answer0) {
            case "C":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "c":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        }else if(questionNum == 6){
        switch (answer0) {
            case "D":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "d":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        } else if(questionNum == 7){
        switch (answer0) {
            case "A":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "a":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        } else if(questionNum == 8){
        switch (answer0) {
            case "c":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "C":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        } else if(questionNum == 9){
        nextQBtn.setText("End Game");
        
        switch (answer0) {
            case "A":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            case "a":
                answerPromptLbl0.setText ("Correct");
                correctScore ++;
                break;
            default:
                answerPromptLbl0.setText ("Incorrect");
                incorrectScore ++;
                break;}
        
       //save name and score to the file
        }else if(questionNum == 10){
             //generate random number and calculate percentage
            
        userNum= (int)Math.round(Math.random()*100+1);
        youAreUserLbl.setText("Your user Number is: " + String.valueOf(userNum));
        perCorrect = ((correctScore /10)*100 );
        perCorrectNum.setText ("%" + perCorrect);
        //change buttons
        submitBtn.setText("Enter Leaderboard");
        scoreFinal= (""+correctScore);   
        File dataFile = new File("Scores.txt");
        FileWriter out;
	BufferedWriter writeFile;
	Scanner input = new Scanner(System.in);
	int score;
	String name;
        
        
        try {
			out = new FileWriter(dataFile,true);
			writeFile = new BufferedWriter(out);
			for (int i = 0; i < 1; i++) {
				name = answer0;
				writeFile.write(name);
				writeFile.newLine();
				writeFile.write(scoreFinal);
				writeFile.newLine();
			}  	
    		writeFile.close();
    		out.close();
    		System.out.println("Data written to file.");
    	} catch (IOException e) {
			System.out.println("Problem writing to file.");
    		System.err.println("IOException: " + e.getMessage());
    	} 
            //display leaderboard from file
        }else if (questionNum==11){
            submitBtn.setText("Exit");
            nextQBtn.setText("Exit");
            jScrollPane1.setVisible(true);
            textOut.setVisible(true);
                File dataFile = new File("scores.txt");
		FileReader in;
		BufferedReader readFile;
		String name;
		String score;
		try {
			in = new FileReader(dataFile);
			readFile = new BufferedReader(in);
    		while ((name = readFile.readLine()) != null ) {
                        
                    textOut.append( name +"\n");
                }
                
			readFile.close();
			in.close();
                
		} catch (FileNotFoundException e) {
			System.out.println("File does not exist or could not be found.");
			System.err.println("FileNotFoundException: " + e.getMessage());
		} catch (IOException e) {
			System.out.println("Problem reading file.");
                        System.err.println("IOException: " + e.getMessage());
    	
                }//end the program
               }else if (questionNum==12){
                    System.exit(0);
                }
           

         //hide submit button after it's pressed    
         submitBtn.setVisible(false);
         nextQBtn.setVisible(true);                
        //calculate and display scores
         numCorrectNum.setText (""+correctScore);
         numIncorrectNum.setText (""+incorrectScore);
         
               
    }//GEN-LAST:event_submitBtnActionPerformed

    private void nextQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQBtnActionPerformed
      //show submit button
        nextQBtn.setVisible(false);
       submitBtn.setVisible(true);
      //increase question by one
        questionNum ++ ;
        //set question and possible answers
        if (questionNum == 0){
            questionLbl0.setText("How many catigories of towels does Monica Have?");
            ansALbl0.setText("A) 9");
            ansBLbl0.setText("B) 7");
            ansCLbl0.setText("C) 11");
            ansDLbl0.setText("D) 16");
            userAnswer0.setText(null);
        } else if (questionNum == 1){
            questionLbl0.setText("What does D.O.A. stand for?");
            ansALbl0.setText("A) Driving Over America");
            ansBLbl0.setText("B) Death Of Accountant");
            ansCLbl0.setText("C) Dead On Arrival");
            ansDLbl0.setText("D) Dying Of Aids");
            userAnswer0.setText(null);
        }else if (questionNum == 2){
            questionLbl0.setText("What is Chandler's Job?");
            ansALbl0.setText("A) Accountant");
            ansBLbl0.setText("B) IT Procurements Manager");
            ansCLbl0.setText("C) Transponster");
            ansDLbl0.setText("D) IT Information Editor");
            userAnswer0.setText(null);
        }else if (questionNum == 3){
            questionLbl0.setText("How many times does Ross get married?");
            ansALbl0.setText("A) 3");
            ansBLbl0.setText("B) 2");
            ansCLbl0.setText("C) 1");
            ansDLbl0.setText("D) 4");
            userAnswer0.setText(null);
        }else if (questionNum == 4){
            questionLbl0.setText("What was Ross's Monkey's name?");
            ansALbl0.setText("A) Marty");
            ansBLbl0.setText("B) Marcel");
            ansCLbl0.setText("C) Muriel");
            ansDLbl0.setText("D) Monty");
            userAnswer0.setText(null);
        }else if (questionNum == 5){
            questionLbl0.setText("Who was Rachel supposed to marry in the first episode? ");
            ansALbl0.setText("A) Paolo");
            ansBLbl0.setText("B) Ross");
            ansCLbl0.setText("C) Barry");
            ansDLbl0.setText("D) Joshua");
            userAnswer0.setText(null);
        }else if (questionNum == 6){
            questionLbl0.setText("How does Joey ask women out?");
            ansALbl0.setText("A) Asks for dinner and a movie");
            ansBLbl0.setText("B) Waaazzzzuuuupppp?");
            ansCLbl0.setText("C) What's goin on? ");
            ansDLbl0.setText("D) How you doin?");
            userAnswer0.setText(null);
        }else if (questionNum == 7){
            questionLbl0.setText("What's Chandler's dad's Las Vegas burlesque show called?");
            ansALbl0.setText("A) Viva Las Gaygas");
            ansBLbl0.setText("B) La Vie En Gay");
            ansCLbl0.setText("C) Cirque De So Gay");
            ansDLbl0.setText("D) Some Gays Over The Rainbow");
            userAnswer0.setText(null);
        }else if (questionNum == 8){
            questionLbl0.setText("Where does Chandler tell Janice he moved to in oreder to avoid her?");
            ansALbl0.setText("A) Kuwait");
            ansBLbl0.setText("B) Sudan");
            ansCLbl0.setText("C) Yemen");
            ansDLbl0.setText("D) Oman");
            userAnswer0.setText(null);
        }else if (questionNum == 9){
            questionLbl0.setText("Where did Monica & Chandler first hook up?");
            ansALbl0.setText("A) London");
            ansBLbl0.setText("B) Birmingham");
            ansCLbl0.setText("C) Paris");
            ansDLbl0.setText("D) L.A.");
            userAnswer0.setText(null);
        }else if (questionNum == 10){
            
            //ask user to submit to the leaderboard
            questionLbl0.setText("Thanks For Playing");
            ansALbl0.setVisible(false);
            ansBLbl0.setVisible(false);
            ansCLbl0.setVisible(false);
            ansDLbl0.setVisible(false);
            answerPromptLbl0.setText("Enter Your name for the leaderboard:");
            userAnswer0.setText(null);
            
          // view leaderboard
        }else if (questionNum == 11){
            questionLbl0.setText("Thanks For Playing");
            answerPromptLbl0.setText("");
            submitBtn.setText("View Leaderboard");
            userAnswer0.setVisible(false);
        }

        
    }//GEN-LAST:event_nextQBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionsScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
            new QuestionsScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ansALbl0;
    private javax.swing.JLabel ansBLbl0;
    private javax.swing.JLabel ansCLbl0;
    private javax.swing.JLabel ansDLbl0;
    private javax.swing.JLabel answerPromptLbl0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextQBtn;
    private javax.swing.JLabel numCorrectLbl;
    private javax.swing.JLabel numCorrectNum;
    private javax.swing.JLabel numIncorrectLbl;
    private javax.swing.JLabel numIncorrectNum;
    private javax.swing.JLabel perCorrectLbl;
    private javax.swing.JLabel perCorrectNum;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel questionLbl0;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextArea textOut;
    private javax.swing.JTextField userAnswer0;
    private javax.swing.JLabel youAreUserLbl;
    // End of variables declaration//GEN-END:variables
}
