/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omsay9559
 */
public class stringMethods extends javax.swing.JFrame {

    /**
     * Creates new form stringMethods
     */
    public stringMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lengthLbl = new javax.swing.JLabel();
        lengthInput = new javax.swing.JTextField();
        LengthBtn = new javax.swing.JButton();
        capsLbl = new javax.swing.JLabel();
        capsInput = new javax.swing.JTextField();
        capsBtn = new javax.swing.JButton();
        fourthSpotLbl = new javax.swing.JLabel();
        fourthSpotInput = new javax.swing.JTextField();
        fourthSpotBtn = new javax.swing.JButton();
        identicalLbl = new javax.swing.JLabel();
        identicalInput1 = new javax.swing.JTextField();
        identicalBtn = new javax.swing.JButton();
        identicalInput2 = new javax.swing.JTextField();
        letterLbl = new javax.swing.JLabel();
        letterInput1 = new javax.swing.JTextField();
        letterInput2 = new javax.swing.JTextField();
        letterBtn = new javax.swing.JButton();
        charactersLbl = new javax.swing.JLabel();
        charactersInput = new javax.swing.JTextField();
        charactersBtn = new javax.swing.JButton();
        replaceLbl = new javax.swing.JLabel();
        replaceInput = new javax.swing.JTextField();
        replaceBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel1.setText("Super String Software");

        lengthLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        lengthLbl.setText("Enter a String. The program will output the number of characters in the String. ");

        lengthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthInputActionPerformed(evt);
            }
        });

        LengthBtn.setText("Find Length");
        LengthBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LengthBtnActionPerformed(evt);
            }
        });

        capsLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        capsLbl.setText("Enter a String using lowercase letters. The program will output the string in all caps. ");

        capsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsInputActionPerformed(evt);
            }
        });

        capsBtn.setText("ALL CAPS");
        capsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsBtnActionPerformed(evt);
            }
        });

        fourthSpotLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        fourthSpotLbl.setText("Enter a String. The program will output the character in the fourth spot. ");

        fourthSpotInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthSpotInputActionPerformed(evt);
            }
        });

        fourthSpotBtn.setText("4th spot");
        fourthSpotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthSpotBtnActionPerformed(evt);
            }
        });

        identicalLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        identicalLbl.setText("Enter 2 Strings. The program will output whether they are identical or not. ");

        identicalInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalInput1ActionPerformed(evt);
            }
        });

        identicalBtn.setText("Identical?");
        identicalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalBtnActionPerformed(evt);
            }
        });

        identicalInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identicalInput2ActionPerformed(evt);
            }
        });

        letterLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        letterLbl.setText("Enter a String and a letter. The program will output whether or not the letter is in the String.");

        letterInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterInput1ActionPerformed(evt);
            }
        });

        letterInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterInput2ActionPerformed(evt);
            }
        });

        letterBtn.setText("Letter found?");
        letterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letterBtnActionPerformed(evt);
            }
        });

        charactersLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        charactersLbl.setText("Enter a String that is at least 8 characters long. The program will output characters 4-6.");

        charactersInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charactersInputActionPerformed(evt);
            }
        });

        charactersBtn.setText("Characters 4-6");
        charactersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charactersBtnActionPerformed(evt);
            }
        });

        replaceLbl.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        replaceLbl.setText("Enter a String that contains atleast 1 \"a\". The program will then replace all occurences of the letter \"a\" with \"x\".");

        replaceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceInputActionPerformed(evt);
            }
        });

        replaceBtn.setText("Replace");
        replaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LengthBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(capsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(capsBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fourthSpotInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fourthSpotBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(identicalInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(identicalInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(identicalBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(letterInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(letterInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(letterBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(charactersInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(charactersBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(replaceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(replaceBtn))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fourthSpotLbl)
                                .addGap(57, 57, 57))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(identicalLbl)
                                .addGap(55, 55, 55)))))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(letterLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(charactersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(lengthLbl))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(capsLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(replaceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lengthLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LengthBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fourthSpotLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourthSpotInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fourthSpotBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(identicalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identicalInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identicalBtn)
                    .addComponent(identicalInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(letterLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letterInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letterBtn)
                    .addComponent(letterInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(charactersLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charactersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charactersBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(replaceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceBtn))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lengthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthInputActionPerformed

    private void LengthBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LengthBtnActionPerformed
        String word1; 
        int length = 0;
      
      word1  =lengthInput.getText();
   
      

        length = (word1.length());
      LengthBtn.setText(" The length is:  " + length +".");
    }//GEN-LAST:event_LengthBtnActionPerformed

    private void capsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsInputActionPerformed

    private void capsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsBtnActionPerformed
        String word, wordCaps; 
        
      
        word  =capsInput.getText();
   
      

        wordCaps = (word.caps());
      LengthBtn.setText(" The word in all caps is:  " + wordCaps +".");
    }//GEN-LAST:event_capsBtnActionPerformed

    private void fourthSpotInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthSpotInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourthSpotInputActionPerformed

    private void fourthSpotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthSpotBtnActionPerformed
        String word1, fourthLetter;
      
      word1  =fourthSpotInput.getText();
   
      

        fourthLetter = (word1.charAt(3));
      fourthSpotBtn.setText(" The fourth letter is:  " + fourthLetter +".");
    }//GEN-LAST:event_fourthSpotBtnActionPerformed

    private void identicalInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identicalInput1ActionPerformed

    private void identicalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identicalBtnActionPerformed

    private void identicalInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identicalInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identicalInput2ActionPerformed

    private void letterInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterInput1ActionPerformed

    private void letterInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterInput2ActionPerformed

    private void letterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letterBtnActionPerformed

    private void charactersInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charactersInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charactersInputActionPerformed

    private void charactersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charactersBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charactersBtnActionPerformed

    private void replaceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceInputActionPerformed

    private void replaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stringMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stringMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LengthBtn;
    private javax.swing.JButton capsBtn;
    private javax.swing.JTextField capsInput;
    private javax.swing.JLabel capsLbl;
    private javax.swing.JButton charactersBtn;
    private javax.swing.JTextField charactersInput;
    private javax.swing.JLabel charactersLbl;
    private javax.swing.JButton fourthSpotBtn;
    private javax.swing.JTextField fourthSpotInput;
    private javax.swing.JLabel fourthSpotLbl;
    private javax.swing.JButton identicalBtn;
    private javax.swing.JTextField identicalInput1;
    private javax.swing.JTextField identicalInput2;
    private javax.swing.JLabel identicalLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lengthInput;
    private javax.swing.JLabel lengthLbl;
    private javax.swing.JButton letterBtn;
    private javax.swing.JTextField letterInput1;
    private javax.swing.JTextField letterInput2;
    private javax.swing.JLabel letterLbl;
    private javax.swing.JButton replaceBtn;
    private javax.swing.JTextField replaceInput;
    private javax.swing.JLabel replaceLbl;
    // End of variables declaration//GEN-END:variables
}
